# Change these first
owner: unraid # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Unraid Home
    url: $URL_UNRAID_HOME
  - name: Unraid Docs
    url: $URL_UNRAID_DOCS
  - name: Unraid Forums
    url: $URL_UNRAID_FORUMS
  - name: My Servers (Staging)
    url: $URL_MY_SERVERS_STAGING
assignees: # Users to assign downtime issues (optional)
  - elibosley

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.unraid.net
  # baseUrl: /status
  logoUrl: https://craftassets.unraid.net/uploads/logos/unraid-stacked-dark.svg
  theme: night
  name: "Unraid Status"
  introTitle: Unraid Status
  introMessage: "To report an issue, reach out using our [Forums](https://forums.unraid.net/), [Discord](https://discord.gg/unraid), or our [website](https://unraid.net/contact)."
  publish: true
  faviconSvg: https://craftassets.unraid.net/static/favicon/favicon.ico?v=1.0
  css: "nav > div { justify-content: center !important; }; .graph { -webkit-mask-image: none !important; mask-image: none !important };"
i18n:
  footer: ""
robotsText: "User-agent: * \n Disallow: /"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
