# Change these first
owner: unraid # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: unraid.net
    url: https://unraid.net/
assignees: # Users to assign downtime issues (optional)
  - elibosley

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://craftassets.unraid.net/uploads/logos/unraid-stacked-dark.svg
  name: Unraid
  introTitle: "Simplicity. Flexibility. Scalability. Modularity. Unraid empowers you to build the system you’ve always wanted using your preferred hardware, software, and operating systems."
  introMessage: This is a status page for Unraid services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
robotsText: "User-agent: * \n Disallow: /"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
